/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package client;

import client.Client;
import client.GUI;
import javax.swing.JComponent;
import javax.swing.JTabbedPane;
import javax.swing.JTextArea;
import javax.swing.JTabbedPane;
/**
 *
 * @author roussfra
 */
public class chatWindow extends Window {

    /**
     * Creates new form chatWindow
     */
    public chatWindow() {
        initComponents();
        this.setVisible(true);
        send_file_jButton.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        onglet_jTabbedPane = new javax.swing.JTabbedPane();
        content_jPanel = new javax.swing.JPanel();
        msg_from_jScrollPane = new javax.swing.JScrollPane();
        msg_from_jTextArea = new javax.swing.JTextArea();
        msg_to_jPanel = new javax.swing.JPanel();
        send_jButton = new javax.swing.JButton();
        send_file_jButton = new javax.swing.JButton();
        msg_to_jScrollPane = new javax.swing.JScrollPane();
        msg_to_jTextArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 400));

        onglet_jTabbedPane.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        content_jPanel.setPreferredSize(new java.awt.Dimension(648, 300));

        msg_from_jTextArea.setColumns(20);
        msg_from_jTextArea.setEditable(false);
        msg_from_jTextArea.setRows(5);
        msg_from_jTextArea.setText("Yet\nAnother\nChat");
        msg_from_jScrollPane.setViewportView(msg_from_jTextArea);

        send_jButton.setText("Send");
        send_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                send_jButtonActionPerformed(evt);
            }
        });

        send_file_jButton.setText("Send File");
        send_file_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                send_file_jButtonActionPerformed(evt);
            }
        });

        msg_to_jScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        msg_to_jTextArea.setColumns(20);
        msg_to_jTextArea.setRows(5);
        msg_to_jTextArea.setText("Message");
        msg_to_jScrollPane.setViewportView(msg_to_jTextArea);

        javax.swing.GroupLayout msg_to_jPanelLayout = new javax.swing.GroupLayout(msg_to_jPanel);
        msg_to_jPanel.setLayout(msg_to_jPanelLayout);
        msg_to_jPanelLayout.setHorizontalGroup(
            msg_to_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(msg_to_jPanelLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(msg_to_jScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 448, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(msg_to_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, msg_to_jPanelLayout.createSequentialGroup()
                        .addComponent(send_jButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, msg_to_jPanelLayout.createSequentialGroup()
                        .addComponent(send_file_jButton, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        msg_to_jPanelLayout.setVerticalGroup(
            msg_to_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, msg_to_jPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(send_jButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(send_file_jButton, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
            .addGroup(msg_to_jPanelLayout.createSequentialGroup()
                .addComponent(msg_to_jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout content_jPanelLayout = new javax.swing.GroupLayout(content_jPanel);
        content_jPanel.setLayout(content_jPanelLayout);
        content_jPanelLayout.setHorizontalGroup(
            content_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(msg_from_jScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 585, Short.MAX_VALUE)
            .addComponent(msg_to_jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        content_jPanelLayout.setVerticalGroup(
            content_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, content_jPanelLayout.createSequentialGroup()
                .addComponent(msg_from_jScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(msg_to_jPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        onglet_jTabbedPane.addTab("tab1", content_jPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(onglet_jTabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 590, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(onglet_jTabbedPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void send_file_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_send_file_jButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_send_file_jButtonActionPerformed

    private void send_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_send_jButtonActionPerformed
        // TODO add your handling code here:
        String old_Text;
        old_Text = msg_from_jTextArea.getText() + "\n" + msg_to_jTextArea.getText();
        msg_from_jTextArea.setText(old_Text);
    }//GEN-LAST:event_send_jButtonActionPerformed

  
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel content_jPanel;
    private javax.swing.JScrollPane msg_from_jScrollPane;
    private javax.swing.JTextArea msg_from_jTextArea;
    private javax.swing.JPanel msg_to_jPanel;
    private javax.swing.JScrollPane msg_to_jScrollPane;
    private javax.swing.JTextArea msg_to_jTextArea;
    private javax.swing.JTabbedPane onglet_jTabbedPane;
    private javax.swing.JButton send_file_jButton;
    private javax.swing.JButton send_jButton;
    // End of variables declaration//GEN-END:variables

    public JTextArea getMsg_from_jTextArea() {
        return msg_from_jTextArea;
    }

    public JTextArea getMsg_to_jTextArea() {
        return msg_to_jTextArea;
    }

    public JTabbedPane getOnglet_jTabbedPane() {
        return onglet_jTabbedPane;
    }
    
}
